name: node-fork-project

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: la_fetch
    environment:
      DATABASE_URL: database_url_here
      PORT: 5001
      ACCESS_TOKEN_SECRET: token_here
    ports:
      - "5001:5001"
    # cpus: 2
    restart: unless-stopped
